SCRIPTS_GAME_DIR = "src/scripts/game_dir/"
SCRIPTS_DIR = "src/scripts/"
UI_DIR = "src/resources/UI/"
JSONS_DIR = "src/resources/jsons/"
MEDIA_DIR = "src/resources/media/"
IMAGE_DIR = "src/resources/UI/"
