SCRIPTS_GAME_DIR = "src/scripts/game_dir/"
SCRIPTS_DIR = "src/scripts/"
UI_DIR = "src/resources/UI/"
JSONS_DIR = "src/resources/jsons/"
MUSIC_DIR = "src/resources/music/"
IMAGE_DIR = "src/resources/UI/"
